<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Cortside.Common.Testing" Version="10.0.507-develop" />
    <PackageReference Include="Cortside.Common.Testing.EntityFramework" Version="10.0.507-develop" />
    <PackageReference Include="Cortside.DomainEvent.Stub" Version="10.0.408-EBPP-5072" />
    <PackageReference Include="Cortside.MockServer.AccessControl" Version="10.0.90-develop" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ReferenceTrimmer" Version="3.5.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Analyzers" Version="4.15.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.30.0.144632">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="WireMock.Net" Version="2.0.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="DistributedLock.FileSystem" Version="1.0.3" />
    <PackageReference Include="Cortside.RestApiClient" Version="10.0.212-develop" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cortside.AspNetCore\Cortside.AspNetCore.csproj" />
  </ItemGroup>
</Project>